[general]
import = [
    "~/.config/alacritty/themes/themes/ashes_light.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[window]
padding = { x = 4, y = 4 }
decorations = "none"
opacity = 0.95
